version: '3.8'

services:
  mlflow:
    image: python:3.9-slim
    container_name: mlflow_server
    ports:
      - "5000:5000"
    volumes:
      - ../mlruns:/mlruns  # Mount the existing mlruns folder
    command: >
      sh -c "
      pip install mlflow &&
      mlflow server --host 0.0.0.0 --port 5000 
      "